# Generated by Django 5.0.4 on 2026-03-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelURI', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('flavor', models.CharField(max_length=100)),
                ('labels', models.JSONField()),
                ('input_signature', models.JSONField()),
                ('output_signature', models.JSONField()),
                ('classification_type', models.CharField(choices=[('binary', 'Binary'), ('multi_classes', 'Multi Classes'), ('multi_labels', 'Multi Labels')], default='binary', max_length=20)),
                ('dataset_path', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
