# Generated by Django 5.0.4 on 2026-03-26 20:55

import Explanation.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explainaing_algo', models.CharField(max_length=100)),
                ('explanation_type', models.CharField(max_length=100)),
                ('explain_input', models.JSONField()),
                ('explain_output', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0), Explanation.models.validate_rating_step])),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='Query.query')),
            ],
        ),
    ]
